### ISSUE TITLE
Removing the Container class

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#11]
The container is meant to read a fits in a generic way, yet I guess this is impossible, because there are too many variations of them. However, what we can do is to provide only the [HDU_to_fits()](https://github.com/ChileanVirtualObservatory/acalib/blob/master/acalib/io/fits.py#L11) function. This way, the fits reading is responsibility of the user (there are a lot of tutorials!), and we only do the transformation to NDData. What do you think?

**Comment by cvalenzu** [comment]
We still need a common data structure for some algorithms that uses a collection of images as input (like staking) o to return a collection of tables and images (like indexing).

**Comment by maray** [comment]
I know... ASYDO also uses the container, but maybe we have to rethink the interface at least.

**Comment by maray** [comment]
I think we should use the generic IO interface for this. http://docs.astropy.org/en/stable/io/unified.html

**Comment by cvalenzu** [comment]
That astropy generic interface look good, we could use something like that.

**Comment by maray** [comment]
This issue is closed because Issue #12 will address this.
