### ISSUE TITLE
Indexing Algorithm Name and Documentation

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#15]
The name of the class "Indexing" is too general. We should change the name to something more clear, and refer in the documentation to the [paper](http://www.sciencedirect.com/science/article/pii/S2213133716000032) and to the [original code](http://ascl.net/1512.010). Probably we should discuss the name with @marcelomendoza

**Comment by cvalenzu** [comment]
CubeIndexer sounds good, but a better idea is to ask @marcelomendoza

**Comment by maray** [comment]
Can we close this issue @Nesus ?

**Comment by cvalenzu** [comment]
We still doen't have change the algorithm name

**Comment by cvalenzu** [comment]
I think the Algorithm will remain as Indexing for now

**Comment by maray** [comment]
Hey!. From the documentation:
https://github.com/ChileanVirtualObservatory/acalib/blob/master/acalib/algorithms/indexing.py#L9

We can name this algorithm RoISE (Region of Interest Seek and Extraction). Do you agree @cvalenzu ?

I reopen this as an issue, because the change will affect @capgadsx and @Legutier at least...
