### ISSUE TITLE
Stacking as an Algorithm

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#27]
There is no `algorithms/stacking.py` file, and no inherited class from Algorithm that implement what is already supposed to be working in the core. Remember to document this class

**Comment by vansimonsen** [comment]
I have created the Stacking class, inherited from Algorithm, but i have a question about the template image as parameter. Actually is a part of the input.

**Comment by maray** [comment]
Ok. I will close this issue, yet I am not sure if the algorithm do not have parameters as I see in the implementation!
