### ISSUE TITLE
Reorganize Imports

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#28]
Python 2 and Python 3 have different import support. 

`from . import x` does not work well in Python 2.7.

We should reorganise imports for hiding `.core` and only showing the UPI, Algorithms and I/O

**Comment by cvalenzu** [comment]
For Python 2.7 using `from __future__ import absolute_import` works fine the imports.

done in 7eb97ba2c21b10d5d0b2d759ab4b6ae27729543b and 1fd8bcf90e4007935006bd22006ac9446be6e727 

Now im looking into hiding the core imports

**Comment by cvalenzu** [comment]
I Think is not possible to hice acalibe.core, but is possible to hide the functions inside the module.
