### ISSUE TITLE
Cython's library import error

### ISSUE THREAD

**Issue by cvalenzu** [ChileanVirtualObservatory/ACALIB#31]
After compiling pycupid and _morph got an error importing the libraries.

`ImportError: /home/tronco/Desktop/acalib/acalib/core/_morph/morph.so: undefined symbol: _Py_ZeroStruct`

This happens only in Python 3, with Python 2 i got no problem importing the libraries.

**Comment by maray** [comment]
Is this fixed already @Nesus ? considering #35 seem so, but it depends on _morph working OK

**Comment by maray** [comment]
Does #38 fix this issue?

**Comment by cvalenzu** [comment]
I think this is fixed now, but still want to test before closing the issue.

**Comment by cvalenzu** [comment]
Fixed in 4fc87f882ebf1c27c8fb02e6fcbc2cae6cb28c5e  (for python 2) b7bd7c16f6793a9cf8fa375d34bc7f15f9d87b30 (for python 3)
