### ISSUE TITLE
Use pyCupid package 

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#35]
We have defined a new repo:

https://github.com/ChileanVirtualObservatory/pycupid

where pyCupid is now.

We need to:
- put this package as dependency of ACALib
- remove from the code the old cupid directory
- change the wrapper functions of FellWalker and ClumpFind at least for using the library

**Comment by cvalenzu** [comment]
Changes done in 4456689381f9444a449a0cd2ebe816f1c3345004
