### ISSUE TITLE
Prepare ACALIB's setup

### ISSUE THREAD

**Issue by capaths** [ChileanVirtualObservatory/ACALIB#4]
Prepare system for installing ACALIB:
- [x] Create setup.py
- [x] Check setup to support PIP standards.

**Comment by cvalenzu** [comment]
We have to add Anaconda support also.

**Comment by maray** [comment]
It does not work in my mac... why?

[setup_bug_macosx_anaconda_python3.5.txt](https://github.com/ChileanVirtualObservatory/acalib/files/559306/setup_bug_macosx_anaconda_python3.5.txt)
