### ISSUE TITLE
Verify and test stacking code

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#40]
The code done by @vansimonsen needs to be reviewed and corrected if needed. Also a notebook with a concrete example should be provided (in the notebooks repository). This is classified as a bug because we already found some problems with the alignments of the images.

**Comment by cvalenzu** [comment]
The algorithm is currently running (doesn't show any exception or error) but still waiting for validation.

**Comment by maray** [comment]
@Autopawn, you will still reimplement the algorithm?

**Comment by autopawn** [comment]
It doesn't seem necessary as the version that I saw that had problems (the one in the `stacking` repo) was not the right one, the right one (the one in `acalib`) could use some more tests but seems to be working.

**Comment by maray** [comment]
Thanks for the info, closing on behalf of #58
