### ISSUE TITLE
Licensing Code

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/ACALIB#52]
We need to protect our code (requirement from our funding agency), so every file need to have the GPL license in the header, plus the GPL files required in the main directory.

An example of such header can be found [here](https://github.com/ChileanVirtualObservatory/display/blob/master/src/packages/display/core.py)

**Comment by cvalenzu** [comment]
Added LICENSE.md in 5a3f40f658cba505e4ec60d4cd67d32df06ec4ac waiting for COPYING.md

**Comment by capgadsx** [comment]
I'm not shure about adding a COPYING.md. As i understand, LICENSE.md and COPYING.md provide the same information about the code license. [Reference](https://stackoverflow.com/a/5678716)

**Comment by maray** [comment]
Not necessary. It is fine with the LICENSE.md (the COPYING was not .md, just txt). Closing.
