### ISSUE TITLE
MemoryError in loadFITS_PrimmaryOnly

### ISSUE THREAD

**Issue by capgadsx** [ChileanVirtualObservatory/ACALIB#55]
When using `loadFITS_PrimmaryOnly()` with big fits files (e.g. ALMA01002186_00_00_00.fits 1.8G) the function crashes with a MemoryError exception in the line:
`hduobject.data = (hduobject.data*bscale) + bzero`

**Comment by cvalenzu** [comment]
Function name change to loadFITS_PrimaryOnly

**Comment by maray** [comment]
Why this function exists in the first place? The code is quite duplicated from HDU_to_NDData, so why not merging them?

**Comment by capgadsx** [comment]
The main difference is in how we open the FITS file, we can merge them to avoid duplicated code.
