### ISSUE TITLE
UPI NDDataRef Errors 

### ISSUE THREAD

**Issue by cvalenzu** [ChileanVirtualObservatory/ACALIB#56]
Before merging the pull request #54 I tested the algorithms, but not all the UPI functions.

Now im trying to use `acalib.moment0` and  I get `AttributeError: 'numpy.float64' object has no attribute 'wcs'`

Maybe is the `@support_nddata` decorator or something else.

**Comment by capgadsx** [comment]
@cvalenzu #61 should fix this, can you test the function?

**Comment by maray** [comment]
This is fixed AFAIK. Closing.
