### ISSUE TITLE
Run Tests in Travis Script

### ISSUE THREAD

**Issue by cvalenzu** [ChileanVirtualObservatory/ACALIB#74]
The script is just for building the wheel for now, we need to install the wheel and run the tests.

**Comment by maray** [comment]
Hum... the tests are passing in travis, can we close?

**Comment by cvalenzu** [comment]
Test added to Travis, and everything running except the automatic packaging

**Comment by cvalenzu** [comment]
Test added to Travis, and everything running except the automatic packaging
